---
name: Bug Report
about: Create a report to help WordServe to improve
title: "bug: "
labels: "bug"
assignees: ""
---

# Bug Report

**WordServe**

<!-- Please specify commit or tag version. -->

**Current behavior:**

<!-- Describe how the bug manifests. -->

**Expected behavior:**

<!-- Describe what the behavior would be without the bug. -->

**Steps to reproduce:**

<!--  Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application. -->

```
insert short code snippets here
```

**Other information:**

<!-- List any other information that is relevant to your issue. Related issues, suggestions on how to fix,  etc. -->
